replicaCount: 1

nameNginx: nginx
nameHttpd: httpd

imageNginx:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"
imageHttpd:
  repository: httpd
  pullPolicy: IfNotPresent
  tag: "latest"


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}