apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameHttpd }}
  labels:
    app: {{ .Values.nameHttpd }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameHttpd }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameHttpd }}
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.imageHttpd.repository }}:{{ .Values.imageHttpd.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}